const projectDetails = {
  mlSentimentAnalysis: {
    name: "mlSentimentAnalysis",
    title: "Sentiment Analysis ML Project",
    projectTime: "",
    projectTitleImg: "path/to/img",
    projectTitleImgAlt: "images description",
    projectTechnologies: ["Python", "Numpy", "Pandas"],
    projectDescription:
      "This is a group project built under the Machine Learning (50.007) module in SUTD.",
    projectElaboration: "BLah BLah BLah  BLah BLahv BLah BLah BLah BLah BLah ",
    projectLinks: ["https://github.com/NathanAW24/food-sharing-app"],
    projectContribution: ["sdfsd", "dfasfs", "afdf"],
    projectAchievements: ["Grade A"],
  },
  ORA: {
    name: "ORA",
    title: "Project ORA",
    projectTime: "",
    projectTitleImg: "path/to/img",
    projectTitleImgAlt: "images description",
    projectTechnologies: ["Next.js", "React.js", "Typescript"],
    projectDescription:
      "A forms submission portal for SUTD Office of Student Life done as a project for the Elements of Software Construction (50.003) module in SUTD.",
    gitHubLink: "https://github.com/NathanAW24/food-sharing-app",
    projectContribution: ["sdfsd", "dfasfs", "afdf"],
    projectAchievements: [],
  },
  tiktokChallenge: {
    name: "tiktokChallenge",
    title: "Group Buy App - TikTok Challenge",
    projectTime: "",
    projectTitleImg: "path/to/img",
    projectTitleImgAlt: "images description",
    projectTechnologies: ["Next.js", "React.js", "Typescript"],
    projectDescription: "This is a group project done for a tiktok hackathon.",
    gitHubLink: "https://github.com/NathanAW24/food-sharing-app",
    projectContribution: ["sdfsd", "dfasfs", "afdf"],
    projectAchievements: [],
  },
  HungryBees: {
    name: "HungryBees",
    title: "HungryBees - Food delivery Sharing App",
    projectTime: "",
    projectTitleImg: "path/to/img",
    projectTitleImgAlt: "images description",
    projectTechnologies: ["java", "andriod"],
    projectDescription:
      "This is a group project built under the information Systems and Programming (50.001) module in SUTD.",
    gitHubLink: "https://github.com/NathanAW24/food-sharing-app",
    projectContribution: ["sdfsd", "dfasfs", "afdf"],
    projectAchievements: [],
  },
  GFSI: {
    name: "GFSI",
    title: "Global Food Security Index Predictive Analysis",
    projectTime: "",
    projectTitleImg: "path/to/img",
    projectTitleImgAlt: "images description",
    projectTechnologies: [
      "Python",
      "Numpy",
      "Pandas",
      "Mathplotlib",
      "Next.js",
      "React.js",
      "Typescript",
    ],
    projectDescription:
      "This is a group project built under the Data Driven World (10.020) module in SUTD.",
    gitHubLink: "https://github.com/NathanAW24/food-sharing-app",
    projectContribution: ["sdfsd", "dfasfs", "afdf"],
    projectAchievements: [],
  },
  designThinkingProject: {
    name: "designThinkingProject",
    title: "Project LIT-TREE-LY ",
    projectTime: "",
    projectTitleImg: "path/to/img",
    projectTitleImgAlt: "images description",
    projectTechnologies: [],
    projectDescription:
      "This is a group project built under the Design Thinking and Inovation (3.007) module in SUTD.",
    gitHubLink: "https://github.com/NathanAW24/food-sharing-app",
    projectContribution: ["sdfsd", "dfasfs", "afdf"],
    projectAchievements: [],
  },
};

export default projectDetails;
